Refactor for better use as external library
operator-framework/operator-manifest-tools pull request #25
Opened 2022-01-21 19:03 UTC by ryantking

Signed-off-by: Ryan King <ryking@redhat.com>

Goal of this PR is to make this repo more usable as an external library.

- [x] Move pinning logic to public package from CLI
- [ ] Replace skopeo binary calls with library calls

2022-01-21 19:12 UTC, joelanford commented on cmd/pinning/extract.go
>  	operatorManifests, err := pullspec.FromDirectory(manifestPath, pullspec.DefaultHeuristic)
Check this error?

2022-01-21 19:14 UTC, jmrodri requested changes
At first glance looks good. There was small place where we seem to be eating an err.

2022-01-21 19:14 UTC, jmrodri commented on cmd/pinning/extract.go
> +	imageNames, err := image.Extract(operatorManifests)
What about the err from the `pullspec.FromDirectory`. I think we're eating an error somewhere.

2022-02-02 02:51 UTC, zach-source commented
The code looks fine from my perspective, only concern I have is that the integration test failed. It looks like the behavior changed from the previous, there used to be files generated for the pinning command that aren't found any longer. This may not be that big of a deal but it was the behavior of the library before it.

2022-02-02 02:53 UTC, zach-source reviewed
Will approve once we can decide on the integration functionality, either fix it or get consensus for removing the file checks there; then it's a merge from me. If no one cares then I'm fine with the files not being generated.

2022-02-03 15:58 UTC, ryantking commented
Hi @zach-source that is what we are trying to determine: are the intermediary files part of a compatibility contract that we would be breaking? If so I can add them back in.

2022-02-19 15:15 UTC, tonytcampbell commented
Hey folks, while we are not using this yet our plan is to migrate from the python version to this version.  With that said we do rely on those intermediary files at the moment.  I think we could eliminate the files in a future version after a bit of refactoring but would love to see them present for now.

2022-04-01 20:23 UTC, zach-source commented
Apologies, I've been MIA due to paternity leave. I'll take a look at making the necessary changes to support the integration features and get this merged. Thanks for the contribution @ryantking

2022-04-04 16:55 UTC, ryantking commented
Not a problem @zach-source, and congratulations! I added back the intermediary files to the CLI `pin` command in order to get this PR moved along. Now, this is just a refactoring PR that adds the nuts and bolts to library functions and out of the CLI commands on top of the `crane` resolver, which is opt-in.

2022-04-04 16:56 UTC, zach-source commented
@ryantking Thanks Ryan, all test are passing now. I'll just wait for @jmrodri to re-review since they had comments you resolved. I'll merge it as soon as we get a thumbs up.

2022-04-04 17:53 UTC, ryantking commented
@zach-source Since this PR really has two components: I rebased the PR into two commits with detailed messages and descriptions. When you decide to merge this PR, I recommend you merge with a commit merge so the individual commits get added.

2022-04-05 15:57 UTC, jmrodri approved these changes

2022-04-05 16:11 UTC, ryantking commented
@zach-source After you merge this, can you also cut a new release?

2022-04-05 18:32 UTC, zach-source commented
@ryantking Does it automatically.

2022-04-05 18:32 UTC, merged

2022-04-05 18:47 UTC, zach-source commented
Well, semiautomaticly. Had to push a tag. Thanks @ryantking